Name: build
SchemaVersion: "1.0"
Triggers:
  - Type: Push
    Branches:
      - main

Actions:
  List_Files:
    Identifier: aws/build@v1.0.0
    Inputs:
      Sources:
        - WorkflowSource
    Configuration:
      Steps:
        - Run: ls -l
  Mvn_Build_And_Deploy:
    DependsOn:
      - List_Files
    Identifier: aws/build@v1.0.0
    Inputs:
      Sources:
        - WorkflowSource
    Outputs:
      AutoDiscoverReports:
        Enabled: true
        ReportNamePrefix: AutoDiscovered
      Artifacts:
        - Name: jar_artifact
          Files:
            - target/*.jar
            - Dockerfile
    Configuration:
      Steps:
        - Run: cp settings.xml $HOME/.m2/settings.xml
        - Run: ls $HOME/.m2/
        - Run: export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain artifact-store-codecatalyst-demo --domain-owner 669608275570 --region ap-northeast-1 --query authorizationToken --output text`
        - Run: mvn deploy
    Compute:
      Type: EC2
    Environment:
      Connections:
        - Role: Admin
          Name: "669608275570"
      Name: TestEnvironment